const json = {
  title:
    "Multidimensional support with assistive technologies for the aging population in India",
  logo: "https://api.surveyjs.io/private/Surveys/files?name=03c23829-5b12-454f-8250-43d13ac2f303",
  logoWidth: "100px",
  logoHeight: "80px",
  logoPosition: "bottom",
  pages: [
    {
      name: "Section-1",
      elements: [
        {
          type: "text",
          name: "S1Q1",
          title: "Identity No",
        },
        {
          type: "text",
          name: "S1Q2",
          title: "Interviewed by: ",
        },
        {
          type: "text",
          name: "S1Q3",
          title: "Place :  District, Town Village ",
        },
        {
          type: "text",
          name: "S1Q4",
          title: "Date",
          inputType: "date",
        },
      ],
      description: "Details of the Research Assistant/Field Investigator: ",
    },
    {
      name: "Section 1.1",
      elements: [
        {
          type: "text",
          name: "S1_1Q1",
          title: "1. Name of Respondent",
          hideNumber: true,
          isRequired: true,
        },
        {
          type: "text",
          name: "S1_1Q2",
          title: "2. Age",
          hideNumber: true,
          isRequired: true,
          inputType: "number",
        },
        {
          type: "radiogroup",
          name: "S1_1Q3",
          title: "3. Gender",
          hideNumber: true,
          isRequired: true,
          choices: [
            {
              value: "item1",
              text: "Male",
            },
            {
              value: "item2",
              text: "Female",
            },
            {
              value: "item3",
              text: "Other",
            },
          ],
        },
        {
          type: "radiogroup",
          name: "S1_1Q4",
          title: "4. Marital status",
          hideNumber: true,
          isRequired: true,
          choices: [
            "Married",
            "Unmarried",
            "Single(divorced)",
            "Single(Separated)",
            "Widowed",
            "Deserted",
          ],
        },
        {
          type: "radiogroup",
          name: "S1_1Q5",
          title: "5. Caste/Social Group",
          isRequired: true,
          choices: ["SC", "ST", "OBC", "General", "Other"],
        },
        {
          type: "radiogroup",
          name: "S1_1Q6",
          title: "6. Religion",
          isRequired: true,
          choices: [
            "Hindu",
            "Muslim",
            "Christian",
            "Sikhism ",
            "Jainism",
            "other",
          ],
        },
        {
          type: "radiogroup",
          name: "S1_1Q7:",
          title: "7. Educational status: ",
          isRequired: true,
          choices: [
            "Illiterate",
            "Primary",
            "High School",
            "Intermediate",
            "College",
            "Degree",
            "Technical education",
            "PG",
          ],
          hasOther: true,
          otherPlaceHolder: "specify",
          otherText: "Any other",
        },
        {
          type: "text",
          name: "S1_1Q8:",
          title: "8. Languages Known (Specify): ",
        },
        {
          type: "radiogroup",
          name: "S1_1Q9:",
          title: "9. Place of Living: ",
          isRequired: true,
          choices: ["Urban", "Semi-Urban", "Rural"],
        },
        {
          type: "text",
          name: "S1_1Q10:",
          title: "10. Mobile/Phone No: ",
          inputType: "number",
        },
        {
          type: "text",
          name: "S1_1Q11:",
          title: "11. Email ID: ",
        },
        {
          type: "radiogroup",
          name: "S1_1Q12",
          title: "12. Job:",
          choices: [
            "Salary     ",
            "Unorganized sector        ",
            "Own business     ",
            "Unemployed",
          ],
        },
        {
          type: "radiogroup",
          name: "S1_1Q13",
          title: "13. Yearly Household Income",
          choices: [
            "Less than 50000       ",
            "50000-100000              ",
            "100000-150000          ",
            "More than 150000",
          ],
        },
        {
          type: "radiogroup",
          name: "S1_1Q14",
          title: "14. Whether Pensioner: ",
          choices: [
            {
              value: "item1",
              text: "Yes",
            },
            {
              value: "item2",
              text: "No",
            },
          ],
        },
        {
          type: "text",
          name: "S1_1Q15:",
          title: "15. Amount of Pension:",
          inputType: "number",
        },
        {
          type: "radiogroup",
          name: "S1_1Q16",
          title: "16. Source of Pension: ",
          choices: ["Government", "Private"],
        },
        {
          type: "radiogroup",
          name: "S1_1Q17",
          title: "17. Family status",
          choices: [
            "Lower class           ",
            "Middle class                ",
            "Upper class   ",
          ],
        },
        {
          type: "radiogroup",
          name: "S1_1Q18",
          title: "18. Status of the  house:",
          choices: ["Own", "Rented"],
          hasOther: true,
          otherText: "Any other (specify)",
        },
        {
          type: "radiogroup",
          name: "S1_1Q19:",
          title: "19. Kind of house: ",
          choices: ["Thatched", "Tiled", "Concrete"],
        },
        {
          type: "radiogroup",
          name: "S1_1Q20",
          title: "20. Is there a water connection in the house?",
          choices: [
            {
              value: "item1",
              text: "Yes",
            },
            {
              value: "item2",
              text: "No",
            },
          ],
        },
        {
          type: "radiogroup",
          name: "S1_1Q21",
          title: "21. Is there a toilet in the house?",
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S1_1Q22",
          title: "22. No of rooms in the house",
          choices: [
            "One room and common toilet ",
            "One room Kitchen and  toilet ",
            "Two rooms Kitchen and toilet ",
            "Three rooms Kitchen and toilet ",
          ],
        },
        {
          type: "radiogroup",
          name: "S1_1Q23",
          title: "23. Type of cooking Fuel used in the house",
          choices: ["Gas", "Stove", "Wood"],
        },
        {
          type: "radiogroup",
          name: "S1_1Q24:",
          title: "24. Whether Living with family:  ",
          choices: ["Near Relation(Spouse/Children/Parents/Siblings)"],
          hasOther: true,
          otherText:
            "Not Near Relations: Anyone other than Blood relations (specify)",
        },
        {
          type: "multipletext",
          name: "S1_1Q25",
          title: "25. No. of members in the family",
          items: [
            {
              name: "Males",
              title: "Males",
            },
            {
              name: "Females",
              title: "Females",
            },
            {
              name: "Children above 19",
              title: "Children above 19",
            },
          ],
        },
        {
          type: "multipletext",
          name: "S1_1Q26",
          title: "26. Dependable children less than 18 ",
          items: [
            {
              name: "Male",
            },
            {
              name: "Female",
            },
          ],
        },
        {
          type: "multipletext",
          name: "S1_1Q27",
          title: "27. Senior citizens in the family Numbers",
          items: [
            {
              name: "Male",
            },
            {
              name: "Female",
            },
          ],
        },
        {
          type: "radiogroup",
          name: "S1_1Q28",
          title: "28. Do you have a separate room /space for yourself?",
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S1_1Q29",
          title: "29. Whether staying in an Institution: ",
          choices: [
            "With Spouse",
            "Without Spouse",
            "With Family members",
            "Without Family members",
            "None/Alone",
          ],
        },
        {
          type: "text",
          name: "S1_1Q30",
          title: "30. In case of financial need who helps you? ",
        },
      ],
      description: "I.\tSocio-demographic details",
    },
    {
      name: "Section-II",
      elements: [
        {
          type: "radiogroup",
          name: "S2Q1",
          title:
            "1.\tWhat is the nearest available health facility near your place which you can reach",
          hideNumber: true,
          choices: [
            "Hospital  (Govt./ Private)",
            "Clinic/Nursing Home  (Govt./ Private)",
            "Private Consultant  (Doctor)",
          ],
        },
        {
          type: "radiogroup",
          name: "S2Q2",
          title:
            "2.How far is the nearest Medical facility available from your place",
          hideNumber: true,
          choices: [
            "Less than 2 KM",
            "Between 3-5 Km",
            "Between 6-10",
            "More than 10 km",
          ],
        },
        {
          type: "radiogroup",
          name: "S2Q3",
          title: "3.\tWho do you approach in case of health need: ",
          hideNumber: true,
          choices: ["Government Hospital", "Private hospital", "Clinic"],
        },
        {
          type: "radiogroup",
          name: "S2Q4",
          title: "4.\tIn case of emergency who do you think will help you.",
          hideNumber: true,
          choices: ["Family Member", "Neighbor", "Relatives", "Institution"],
          hasOther: true,
          otherText: "Any other (Specify)",
        },
        {
          type: "checkbox",
          name: "S2Q5",
          title:
            "5.\tDo you have regular visits for your health checkup from any of the following on a regular basis?",
          hideNumber: true,
          choices: [
            "Doctors ",
            "Physiotherapists",
            "Diagnostics",
            "Govt. appointed health personnel",
          ],
        },
        {
          type: "radiogroup",
          name: "S2Q6",
          title: "6.\tHow do you monitor your health",
          hideNumber: true,
          choices: [
            "Regular checkups",
            "As and when you are sick",
            "Only when you are very sick",
          ],
        },
        {
          type: "radiogroup",
          name: "S2Q7",
          title: "7.\tWho takes care of you when sick",
          hideNumber: true,
          choices: [
            "No one",
            "My spouse",
            "My children",
            "My siblings",
            "My relatives",
            "Neighbors",
            "Friends",
          ],
        },
        {
          type: "radiogroup",
          name: "S2Q8",
          title: "8.\tAre you aware of the indications of your sickness",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
      ],
      title: "II. Medical resources/Facilities available ",
    },
    {
      name: "Section-III",
      elements: [
        {
          type: "radiogroup",
          name: "S3Q1",
          title: "1. How do you rate your health status? ",
          hideNumber: true,
          isRequired: true,
          choices: [
            {
              value: "Very Good",
              text: "Very Good",
            },
            {
              value: "Good",
              text: " Good",
            },
            {
              value: "Satisfactory",
              text: "Satisfactory",
            },
            {
              value: "Not So Good",
              text: "Not So Good",
            },
            {
              value: "Bad",
              text: "Bad",
            },
          ],
        },
        {
          type: "checkbox",
          name: "S3Q2",
          title: "2. Any health problem: ",
          hideNumber: true,
          isRequired: true,
          choices: [
            {
              value: "Diabetic",
              text: "Diabetic",
            },
            {
              value: "Hypertension (Blood Pressure)",
              text: "Hypertension (Blood Pressure)",
            },
            {
              value: " Asthma",
              text: " Asthma",
            },
            {
              value: "Skin problems ",
              text: "Skin problems ",
            },
            {
              value: "Digestive System Problem",
              text: "Digestive System Problem",
            },
          ],
          hasOther: true,
          otherText: "Any Other (Specify)",
        },
        {
          type: "radiogroup",
          name: "S3Q3",
          title: "3. Please mention the duration of your health problem",
          hideNumber: true,
          choices: [
            {
              value: "Less than 1 year  ",
              text: "Less than 1 year  ",
            },
            {
              value: "1-5 Years",
              text: "1-5 Years",
            },
            {
              value: "5-10 Years",
              text: "5-10 Years",
            },
          ],
        },
        {
          type: "radiogroup",
          name: "S3Q4",
          title: "4. Are you under medication for your health Problem:  ",
          hideNumber: true,
          isRequired: true,
          choices: [
            {
              value: "Yes",
              text: "Yes",
            },
            {
              value: "No",
              text: "No",
            },
          ],
        },
        {
          type: "radiogroup",
          name: "S3Q5",
          title: "5. Have you undergone any surgery :",
          hideNumber: true,
          isRequired: true,
          choices: [
            {
              value: "No",
              text: "No",
            },
          ],
          choicesOrder: "desc",
          hasOther: true,
          otherPlaceHolder: "Minor or Major and When?",
          noneText: "Yes(Major)",
          otherText: "Yes ",
        },
        {
          type: "radiogroup",
          name: "S3Q6",
          title: "6.\tAre you aware of what are the medicines that you take?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S3Q7",
          title: "7.\tDo you know for what purpose you take what medicine?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S3Q8",
          title:
            "8. Are you aware of any Psychological Problems that you faced",
          hideNumber: true,
          choices: ["Yes", "No"],
          otherPlaceHolder: "Please mention",
          otherText: "Yes",
        },
        {
          type: "text",
          name: "S3Q9",
          title: "9.\tIf Yes, please mention: ",
          hideNumber: true,
        },
        {
          type: "text",
          name: "S3Q10",
          title:
            "10.\tAre you able to sleep and eat as usual? (specify if any problem)",
          hideNumber: true,
        },
        {
          type: "text",
          name: "S3Q11",
          title: "11.\tDo you feel worried about any issue/s: (specify)",
          hideNumber: true,
        },
        {
          type: "text",
          name: "S3Q12",
          title: "12.\tDo you have any fears? (specify)",
          hideNumber: true,
        },
        {
          type: "radiogroup",
          name: "S3Q13",
          title: "13.\tIs there any feeling of loneliness at any time? ",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S3Q14",
          title: "14.\tIf yes, specify how often: ",
          hideNumber: true,
          choices: ["Always", "Often", "Sometimes", "Rarely", "Never"],
        },
        {
          type: "radiogroup",
          name: "S3Q15",
          title: "15. Do you have people of your age group nearby?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "text",
          name: "S3Q16",
          title: "16.\tHow often do you meet them?",
          hideNumber: true,
        },
        {
          type: "radiogroup",
          name: "S3Q17",
          title: "17.\tAre you in touch with relatives or friends?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "checkbox",
          name: "S3Q18",
          title: "18.\tHow do you contact them:",
          hideNumber: true,
          choices: ["Landline", "Mobile", "Word of mouth"],
        },
        {
          type: "radiogroup",
          name: "S3Q19",
          title: "19.\tDo you have any kind of social gatherings: ",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "text",
          name: "S3Q20",
          title: "20.\tIf yes: •\tWhat kind of gatherings do you have?",
          hideNumber: true,
        },
        {
          type: "text",
          name: "S3Q20_1",
          title: "20.1. Who interacts with you often? Specify who?",
          hideNumber: true,
        },
        {
          type: "text",
          name: "S3Q20_2",
          title:
            "20.2. In case of  social   support  who   comes to your help?  ",
          hideNumber: true,
        },
      ],
      title: "III.\tBio-Psycho-Social Health Profile",
    },
    {
      name: "Section-IV",
      elements: [
        {
          type: "checkbox",
          name: "S4Q1",
          title: "1.\tWhat are the gadgets that you use:",
          hideNumber: true,
          choices: [
            "Mobile",
            "Tablet",
            "Computer: Desktop",
            "Computer: Personal Laptop",
          ],
        },
        {
          type: "radiogroup",
          name: "S4Q2",
          title: "2.\tWhat kind of Mobile do you use: ",
          hideNumber: true,
          choices: ["Ordinary Phone", "Smart phone"],
        },
        {
          type: "radiogroup",
          name: "S4Q3",
          title: "3. Do you use Internet?",
          hideNumber: true,
          choices: ["Yes ", "No"],
        },
        {
          type: "text",
          name: "S4Q4",
          title: "4.\tIf yes, How many hours in a day?",
          hideNumber: true,
          inputType: "number",
        },
        {
          type: "radiogroup",
          name: "S4Q5",
          title: "5.\tWhere do you use the internet: ",
          hideNumber: true,
          choices: ["At home", "In cyber café"],
          hasOther: true,
          otherPlaceHolder: "specify",
          otherText: "Any other",
        },
        {
          type: "checkbox",
          name: "S4Q6",
          title: "6.\tAre you using",
          hideNumber: true,
          choices: ["Whatsapp", "Facebook", "Snapchat", "Twitter", "Telegram"],
          hasOther: true,
          otherPlaceHolder: "specify",
          otherText: "Any other ",
        },
        {
          type: "radiogroup",
          name: "S4Q7",
          title: "7.\tDo you know how to use Computers?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S4Q8",
          title: "8.\tDo you use email?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S4Q9",
          title: "9.\tDo you use internet to find out about Health issues?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S4Q10",
          title:
            "10.\tAre you aware of any mobile app that tells you about the health issues?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S4Q11",
          title: "11.\tDo you watch You Tube",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "checkbox",
          name: "S4Q12",
          title:
            "12.\tIf yes, What type of programmes do you watch in You Tube: ",
          hideNumber: true,
          choices: ["Entertainment", "Health", "Religious", "News", "Sport"],
          hasOther: true,
          otherText: "Any other (specify)",
        },
        {
          type: "radiogroup",
          name: "S4Q13",
          title: "13.\tAre you aware of  Video Calls?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "checkbox",
          name: "S4Q14",
          title: "14.\tIf yes, Why do you use them: ",
          hideNumber: true,
          choices: [
            "To talk to Children/Grandchildren",
            "Other family Members",
            "Friends",
            "Consultations",
          ],
          hasOther: true,
          otherText: "Any other (specify)",
        },
        {
          type: "checkbox",
          name: "S4Q15",
          title: "15.\tHow do you make a video call",
          hideNumber: true,
          choices: ["Skype", "Whats app", "Duo", "Facetime"],
          hasOther: true,
          otherText: "Any other (specify)",
        },
        {
          type: "checkbox",
          name: "S4Q16",
          title: "16.\tWhat language do you use while using technology: ",
          hideNumber: true,
          choices: ["English", "Vernacular", "Hindi "],
        },
      ],
      title: "IV.\tKnowledge and Use of Technology",
    },
    {
      name: "Section-V(A)",
      elements: [
        {
          type: "radiogroup",
          name: "S5AQ1",
          title: "1. What was the job that you were doing before Covid 19",
          hideNumber: true,
          choices: [
            "Salary     ",
            "Unorganized sector        ",
            "Own business     ",
            "Unemployed",
          ],
        },
        {
          type: "radiogroup",
          name: "S5AQ2",
          title: "2. Has the Covid 19 impacted your job",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "checkbox",
          name: "S5AQ3",
          title: "3. How are you managing with finances?",
          hideNumber: true,
          choices: [
            "Income from job              ",
            "Savings                  ",
            "Borrowing from relatives     ",
            "Borrowing from money lenders",
          ],
        },
        {
          type: "radiogroup",
          name: "S5AQ4",
          title: "4. How do you see the future ",
          hideNumber: true,
          choices: ["Same     ", "Bleak        ", "A change"],
        },
        {
          type: "radiogroup",
          name: "S5AQ5",
          title: "5. How do you plan to deal with this period of uncertainty",
          hideNumber: true,
          choices: ["No plan             ", "Waiting for things to clear"],
        },
        {
          type: "radiogroup",
          name: "S5AQ6",
          title: "6. Does the future scare you",
          hideNumber: true,
          choices: ["Yes", "No", "Cannot Say"],
        },
        {
          type: "radiogroup",
          name: "S5AQ7",
          title: "7. Have you borrowed money  in this period",
          hideNumber: true,
          choices: ["Yes", "No ", "Cannot say "],
        },
        {
          type: "radiogroup",
          name: "S5AQ8",
          title: "8. What is the amount of money you borrowed",
          hideNumber: true,
          choices: [
            "Less than  Rs. 5000",
            "Rs 5001 – 10,000",
            "10,001 to 20,000",
            "20001 -50, 000",
            "More than 50,000",
          ],
        },
        {
          type: "radiogroup",
          name: "S5AQ9",
          title: "9. From whom have you borrowed money",
          hideNumber: true,
          choices: ["Family/Friends", "Bank", "Private money lender"],
        },
        {
          type: "text",
          name: "S5AQ10",
          title: "10. Notes by the researcher on economic aspect",
          hideNumber: true,
        },
      ],
      title: "HEALTH  AND STRESS DURING THE TIMES OF CORONA",
      description: "A.Economic Aspect",
    },
    {
      name: "Section-V(B)",
      elements: [
        {
          type: "radiogroup",
          name: "S5BQ1",
          title: "1.\tWhat impact it had on women’s work at home",
          hideNumber: true,
          choices: [
            "It has increased",
            "It has decreased",
            "It is the same",
            "Cannot tell",
          ],
        },
        {
          type: "multipletext",
          name: "S5BQ2",
          title:
            "2.\tHow many adults and children do you have to take care of during this pandemic",
          hideNumber: true,
          items: [
            {
              name: "S5BQ2.1",
              title: "Adults Above 60 ",
            },
            {
              name: "S5BQ2.2",
              title: "Children below five",
            },
          ],
        },
        {
          type: "radiogroup",
          name: "S5BQ3",
          title: "3. What is the Impact on care work",
          choices: [
            "It has increased",
            "It has decreased",
            "It is the same",
            "Cannot tell",
          ],
        },
        {
          type: "radiogroup",
          name: "S5BQ4",
          title:
            "4. Do you know of any domestic violence case in your neighborhood",
          hideNumber: true,
          choices: ["Yes", "No ", "Cannot answer"],
        },
        {
          type: "radiogroup",
          name: "S5BQ5",
          title:
            "5.\tIs domestic violence a frequent occurrence in your neighborhood",
          hideNumber: true,
          choices: ["Yes", " No ", "Cannot answer"],
        },
        {
          type: "radiogroup",
          name: "S5BQ6",
          title:
            "6.\tDo you feel insecure. Is there Domestic violence in your own family",
          hideNumber: true,
          choices: ["Yes", "No ", "Cannot answer"],
        },
        {
          type: "radiogroup",
          name: "S5BQ7",
          title: "7.\tHow do you deal with this",
          hideNumber: true,
          choices: [
            "Myself",
            "Tell my neighbors",
            "Get community hep",
            "Made a complaint ",
          ],
        },
        {
          type: "radiogroup",
          name: "S5BQ8",
          title: "8.\t Where are you children below nineteen studying",
          hideNumber: true,
          choices: ["Government", "Private", "Madrasas"],
        },
        {
          type: "radiogroup",
          name: "S5BQ9",
          title: "9.\tAre the schools functioning",
          hideNumber: true,
          choices: ["Yes", "No", "Cannot say"],
        },
        {
          type: "radiogroup",
          name: "S5BQ10",
          title: "10.\tAre your children having online classes",
          hideNumber: true,
          choices: ["Yes", "No ", "Cannot say"],
        },
        {
          type: "radiogroup",
          name: "S5BQ11",
          title:
            "11.\tDo your children have smart phones. If yes How many in the home",
          choices: ["No"],
          hasOther: true,
          otherPlaceHolder: "How many",
          otherText: "Yes",
        },
        {
          type: "radiogroup",
          name: "S5BQ12",
          title:
            "12.\tDo you children have lap tops, computers If yes How many in the home",
          hideNumber: true,
          choices: ["No"],
          hasOther: true,
          otherPlaceHolder: "How many",
          otherText: "Yes",
        },
        {
          type: "radiogroup",
          name: "S5BQ13",
          title:
            "13.\tWould you say your health in general is excellent, very good, good, fair, or poor",
          hideNumber: true,
          choices: ["Excellent", "Very good", "Good", "Fair", "Poor"],
        },
        {
          type: "text",
          name: "S5BQ14",
          title: "14.\tNotes of the researcher on social aspect",
          hideNumber: true,
        },
      ],
      title: "B.\tSocial Aspect",
    },
    {
      name: "Section-V(C)",
      elements: [
        {
          type: "radiogroup",
          name: "S5CQ1",
          title:
            "1.\tWe’d like to know how much you trust people in your neighbourhood. Generally speaking, would you say that you can trust all the people  most of the people, some of the people, or none of the people in your neighborhood?",
          hideNumber: true,
          choices: ["All     ", "Most          ", "Some          ", "None"],
        },
        {
          type: "radiogroup",
          name: "S5CQ2",
          title:
            "2.\tIn the past month, how often did you talk with any of your neighbours?",
          hideNumber: true,
          choices: [
            "Basically, every day     ",
            "A few times a week  ",
            "A few times a month   ",
            "Once a month  ",
            "Not at all ",
            "Not sure",
          ],
        },
        {
          type: "radiogroup",
          name: "S5CQ3",
          title:
            "3. What do you use to communicate with your neighbours, family friends",
          hideNumber: true,
          choices: [
            "Nothing",
            "Talk to them",
            "Phone",
            "Social Media",
            "All three",
          ],
        },
        {
          type: "radiogroup",
          name: "S5CQ4",
          title:
            "4.\tIn the past month, how often did you communicate with friends and family by phone, text, email, app, or using the Internet?",
          hideNumber: true,
          choices: [
            "Basically every day",
            "A few times a week",
            "A few times a month ",
            "Once a month",
            "Not at all",
            "Not sure",
          ],
        },
        {
          type: "radiogroup",
          name: "S5CQ5",
          title:
            "5. Do you support the  government measures to restrict the movement of people to curb the spread of Coronavirus (COVID-19)",
          hideNumber: true,
          choices: ["Yes", "No ", "Cannot say"],
        },
        {
          type: "radiogroup",
          name: "S5CQ6",
          title:
            "6.\tDo you think you have become more religious in these past months",
          hideNumber: true,
          choices: ["Yes", "No ", "Cannot say"],
        },
        {
          type: "radiogroup",
          name: "S5CQ7",
          title: "7. How do you pray now",
          hideNumber: true,
          choices: [
            "As before",
            "At home alone",
            "With few friends",
            "Family members",
          ],
        },
        {
          type: "radiogroup",
          name: "S5CQ8",
          title: "8.\tHow often do you pray now",
          hideNumber: true,
          choices: ["Every day", "In a week ", "In a month"],
        },
        {
          type: "radiogroup",
          name: "S5CQ9",
          title: "9.\tWhat are the new ways of networking in the community?",
          hideNumber: true,
          choices: [
            "Listening to talks by elders",
            "Meeting others once a while ",
            "Phone talks",
            "On Television",
          ],
        },
        {
          type: "radiogroup",
          name: "S5CQ10",
          title: "10. Do you get any  support from your  community?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "checkbox",
          name: "S5CQ11",
          title: "11. What kind of support do you get from your community",
          hideNumber: true,
          choices: ["Financial", "Moral", "Religious", "Medical"],
        },
        {
          type: "radiogroup",
          name: "S5CQ12",
          title:
            "12.\tDo you see your community as being very radical. Is this true.",
          hideNumber: true,
          choices: ["Yes", "No", "Not sure ", "Cannot say"],
        },
        {
          type: "radiogroup",
          name: "S5CQ13",
          title: "13.\tDo you  justify being more radical ?",
          hideNumber: true,
          choices: ["Yes", "No", "Not sure", "Cannot say"],
        },
        {
          type: "radiogroup",
          name: "S5CQ14",
          title:
            "14.\tDo you think people are misinterpreting religiosity to radicalism",
          hideNumber: true,
          choices: ["Yes", "No", "Not sure", "Cannot say"],
        },
        {
          type: "checkbox",
          name: "S5CQ15",
          title: "15.\tWhat do you see as the problem of the community",
          hideNumber: true,
          choices: ["Economic", "Social", "Religious", "Educational "],
        },
        {
          type: "radiogroup",
          name: "S5CQ16",
          title:
            "16.\tDo you think the Government has not done enough for you all during these difficult times",
          hideNumber: true,
          choices: ["Yes", "No ", "Cannot say"],
        },
        {
          type: "checkbox",
          name: "S5CQ17",
          title: "17.\tWhat do you expect the Government to do for you?",
          hideNumber: true,
          choices: [
            "Provide financial help",
            "Provide jobs",
            "Medical help",
            "Help in education",
          ],
        },
        {
          type: "radiogroup",
          name: "S5CQ18",
          title: "18.\tDo you feel cheated by your leaders",
          hideNumber: true,
          choices: ["Yes", "No ", "Cannot say"],
        },
        {
          type: "radiogroup",
          name: "S5CQ19",
          title:
            "19.\tWill you vote for a person of a different party if you are not happy with your community leaders",
          hideNumber: true,
          choices: ["Yes", "No ", "Cannot say"],
        },
        {
          type: "checkbox",
          name: "S5CQ20",
          title:
            "20.\tAre you facing deprivation in access to the following things during the pandemic?",
          hideNumber: true,
          choices: ["Food", "Water", "Medical health", "Friends and relatives"],
        },
        {
          type: "matrix",
          name: "S5CQ21",
          title:
            "21.\tHas pandemic/lockdown affected the following activities in your occupation?",
          hideNumber: true,
          columns: [
            "Increased                     ",
            "Decreased                          ",
            "No effect",
          ],
          rows: ["Movement", "Prices", "Production", "Marketing  "],
        },
        {
          type: "radiogroup",
          name: "S5CQ22",
          title:
            "22.\tIf involved in casual labour activities or salaried job, are you unemployed during the pandemic",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "matrix",
          name: "S5CQ23",
          title:
            "23.\tHow has coronavirus affected your hours in the following work?",
          columns: ["Increased", "Decreased", "No impact"],
          rows: ["Cooking ", "Cleaning", "Care of children", "Care of elderly"],
        },
        {
          type: "radiogroup",
          name: "S5CQ24",
          title: "24.\tHave migrants returned to your village?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S5CQ25",
          title:
            "25.\t   Do you have any alternative livelihood option during the pandemic to sustain your needs?",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S5CQ26",
          title:
            "26.\tHas is the children's education affected during the pandemic",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S5CQ27",
          title: "27.\tDo your children attend online classes",
          hideNumber: true,
          choices: ["Yes", "No"],
        },
        {
          type: "radiogroup",
          name: "S5CQ28",
          title: "28.\tHow do they attend this: ",
          hideNumber: true,
          choices: ["Computers", "Mobiles", "Smart phone"],
        },
        {
          type: "radiogroup",
          name: "S5CQ29",
          title:
            "29.\tAre pregnant women in your house able to access the following during the pandemic? ",
          hideNumber: true,
          choices: ["Hospitals", "Doctors", "Anganwadi Centers "],
        },
      ],
      title: "C.\tCultural Aspect",
    },
    {
      name: "Section-V(D)",
      elements: [
        {
          type: "checkbox",
          name: "S5DQ1",
          title: "1. During the pandemic time what were your fears",
          hideNumber: true,
          choices: [
            "Health related",
            "Loneliness",
            "Financial",
            "Fear of death",
          ],
        },
        {
          type: "radiogroup",
          name: "question7",
          title: "S5DQ2",
          hideNumber: true,
          choices: ["Yes", "No", "Cannot answer"],
        },
        {
          type: "radiogroup",
          name: "S5DQ3",
          title: "3.\tHow do you deal with this",
          hideNumber: true,
          choices: [
            "Myself",
            "Tell my neighbours",
            "Get community hep",
            "Make a complaint ",
          ],
        },
        {
          type: "radiogroup",
          name: "S5DQ4",
          title:
            "4.\tWould you say your health in general is excellent, very good, good, fair, or poor",
          hideNumber: true,
          choices: ["Excellent", "Very good", "Good", "Fair", "Poor"],
        },
        {
          type: "radiogroup",
          name: "S5DQ5",
          title: "5.\tHave you during these recent times",
          hideNumber: true,
          choices: [
            "Felt nervous, anxious, or on edge ",
            "Felt depressed ",
            "Felt lonely",
            "Felt hopeless about the future ",
          ],
        },
        {
          type: "checkbox",
          name: "S5DQ6",
          title:
            "6.\tDid you experience any of these physical reactions when you heard about the Corona Virus in your neighbourhood.",
          hideNumber: true,
          choices: [
            "Sweating",
            "Trouble breathing",
            "Nausea ",
            "Pounding heart ",
            "No reaction",
          ],
        },
        {
          type: "radiogroup",
          name: "S5DQ7",
          title:
            "7.\tDue to have a sense of insecurity  due to Corona much more",
          hideNumber: true,
          choices: ["Yes", "Always felt insecurity", "Cannot say"],
        },
        {
          type: "radiogroup",
          name: "S5DQ8",
          title:
            "8.\tAre you  worried  that your  food would run out before you  got money to buy more ",
          hideNumber: true,
          choices: ["Often true", "Sometimes true ", "Never true "],
        },
        {
          type: "radiogroup",
          name: "S5DQ9",
          title:
            "9.\tIn the past few  month, how often have you been upset because of something that happened unexpectedly?",
          hideNumber: true,
          choices: [
            "Never",
            "Almost Never",
            "Sometimes",
            "Fairly Often",
            "Very Often",
          ],
        },
        {
          type: "radiogroup",
          name: "S5DQ10",
          title:
            "10.\tIn the last month, how often have you felt that you were unable to control the important things in your life?",
          hideNumber: true,
          choices: [
            "Never",
            "Almost Never",
            "Sometimes",
            "Fairly Often",
            "Very Often",
          ],
        },
        {
          type: "radiogroup",
          name: "S5DQ11",
          title:
            "11. In the last month, how often have you felt difficulties were piling up so high that you could not overcome them?",
          hideNumber: true,
          choices: [
            "Never",
            "Almost Never",
            "Sometimes",
            "Fairly Often",
            "Very Often",
          ],
        },
        {
          type: "radiogroup",
          name: "S5DQ12",
          title: "12.\tHave you felt alienated in this situation?",
          hideNumber: true,
          choices: ["Yes", "No ", "Cannot say"],
        },
        {
          type: "radiogroup",
          name: "S5DQ13.",
          title: "13.\tHow do you  see the future?.",
          hideNumber: true,
          choices: ["Same as before. No change", "Dark", "Hopeful "],
        },
      ],
      title: "D.\tPsychological Aspect",
    },
    {
      name: "Section-VI(A)",
      elements: [
        {
          type: "radiogroup",
          name: "S6AQ0",
          title: "Your quality of life as a whole is:",
          hideNumber: true,
          choices: ["Very good", "Good", "Alright", "Bad", "Very bad"],
        },
        {
          type: "radiogroup",
          name: "S6AQ1",
          title: "1. I enjoy my life overall",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ2",
          title: "2. I am happy much of the time.\t",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ3",
          title: "3.  I look forward to the future",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ4",
          title: "4. Life makes me fell low.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ5",
          title: "5. I have a lot of physical Energy.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ6",
          title: "6. Pain affects my well-being.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ7",
          title: "7. My health restricts me from looking myself or my home.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ8",
          title: "8. I am healthy enough to move around the house and outside.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ9",
          title: "9. My family, friends or neighbors would help me if needed.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ10",
          title:
            "10. I would like more companionship or contact with other people.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ11",
          title: "11. I have someone who gives me love and affection.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ12",
          title: "12. I’d like more people to enjoy life with.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ13",
          title: "13. I have my children around which is Important.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ14",
          title: "14. I am healthy enough to have my independence over life.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ15",
          title: "15. I have freedom to do what I want to do.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ16",
          title:
            "16. The cost of things compared to my pension/ income restricts my life.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ17",
          title:
            "17. I have a lot of control over the important things in my life.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ18",
          title: "18. I feel safe where I live.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ19",
          title:
            "19. The local shops, services and facilities are good overall.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ20",
          title: "20. I get pleasure from my home.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ21",
          title: "21. I find my neighborhood friendly.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ22",
          title: "22. I take life as it comes and make the best of things.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ23",
          title: "23. I feel lucky compared to most people.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ24",
          title: "24. I tend to look on the bright side.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ25",
          title:
            "25. If my health limits social/leisure activities, then I will compensate and find something else I can do.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ26",
          title: "26. I have enough money to pay for household bills.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ27",
          title:
            "27. I have enough money to pay for household repairs or help needed in the house.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ28",
          title: "28. I can afford to buy what I want to.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ29",
          title: "29. I cannot afford to do things I would enjoy.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ30",
          title:
            "30. I have social or leisure activities/hobbies that I enjoy doing.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ31",
          title: "31. I try to stay involved with things.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ32",
          title:
            "32. I do paid or unpaid work or activities that give me a role in life.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ33",
          title:
            "33. I have responsibilities to others that restrict my social or leisure activities.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ34",
          title:
            "34. Religion, belief or philosophy is important to my quality of life.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "radiogroup",
          name: "S6AQ35",
          title:
            "35. Cultural/religious events/festivals are important to my quality of life.",
          hideNumber: true,
          choices: [
            "Strongly agree",
            "Agree",
            "Neither agree or disagree",
            "Disagree",
            "Strongly disagree",
          ],
        },
        {
          type: "multipletext",
          name: "S6AQ36",
          title:
            "36.Below are five statements that you may agree or disagree with. Using the 1 - 7 scale below, indicate your agreement with each item by placing the appropriate number on the line preceding that item. Please be open and honest in your responding.\n•\t7 - Strongly agree \n•\t6 - Agree \n•\t5 - Slightly agree \n•\t4 - Neither agree nor disagree \n•\t3 - Slightly disagree \n•\t2 - Disagree \n•\t1 - Strongly disagree\n",
          hideNumber: true,
          items: [
            {
              name: "S6AQ36_1",
              title: "In most ways my life is close to my ideal. ",
            },
            {
              name: "S6AQ36_2",
              title: "The conditions of my life are excellent.",
            },
            {
              name: "S6AQ36_3",
              title: "I am satisfied with my life.",
            },
            {
              name: "S6AQ36_4",
              title:
                "So far I have gotten the important things I want in life.",
            },
            {
              name: "S6AQ36_5",
              title:
                "If I could live my life over, I would change almost nothing.",
            },
          ],
        },
      ],
      title: "QUALITY OF LIFE",
      description:
        "Please indicate the extent to which you agree or disagree with each of the\nfollowing statements.\nTick one box in each row\n",
    },
    {
      name: "Section VI(B)",
      elements: [
        {
          type: "text",
          name: "S6BQ1",
          title:
            "1.\tResearcher’s observations on the  Profile of the  person.",
          hideNumber: true,
        },
        {
          type: "text",
          name: "S6BQ2",
          title: "2.\tResearcher’s observations on the  Health Infrastructure.",
          hideNumber: true,
        },
        {
          type: "multipletext",
          name: "S6BQ3",
          title: "3.\tProblems related to health: ",
          hideNumber: true,
          items: [
            {
              name: "S6BQ3_1",
              title: "Physical",
            },
            {
              name: "S6BQ3_2",
              title: "Psychological",
            },
            {
              name: "S6BQ3_3",
              title: "Social",
            },
          ],
        },
        {
          type: "multipletext",
          name: "S6BQ4",
          title: "4.\tTheir expectations about health facilities",
          hideNumber: true,
          items: [
            {
              name: "S6BQ4_1",
              title: "a)\tTypes of facilities",
            },
            {
              name: "S6BQ4_2",
              title: "b)\tDistance",
            },
            {
              name: "S6BQ4_3",
              title:
                "c)\tPeople of Organisations who help them in providing health facilities",
            },
          ],
        },
        {
          type: "text",
          name: "S6BQ5",
          title:
            "5.\tAre they using any technology: Mobile/Computer/Internet/Social Media.",
        },
        {
          type: "text",
          name: "S6BQ5_1",
          title: "6.\tIf Yes, how does this technology help them?",
          hideNumber: true,
        },
      ],
      title: "PART-B",
    },
  ],
  showProgressBar: "bottom",
};

export default json;
